# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: kjintroverted/go-node
    working_directory: ~/dragon-ui
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b8:78:e9:fe:e2:dc:58:45:d2:36:b5:5e:a1:4a:be:c0"
      - run: npm i
      - run: cd .. && git clone git@github.com:kjintroverted/dnd-build.git build
      - run: cp ../build/secret_firebase.json src/secret_auth_config.json
      # Add Tests
      - run: npm run build:local

  deploy:
    docker:
      - image: kjintroverted/go-node
    working_directory: ~/dragon-ui
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b8:78:e9:fe:e2:dc:58:45:d2:36:b5:5e:a1:4a:be:c0"
            - "d3:20:fd:75:cf:47:ad:45:f1:92:29:51:c8:44:59:88"
      - run: cd .. && git clone git@github.com:kjintroverted/dnd-build.git build
      - run: cp ../build/secret_firebase.json src/secret_auth_config.json
      - run: npm i
      - run: npm run build:local
      - run: rm -rf .git
      - run: echo "https://dungeon.wkgreen.dev" > ./build/CNAME
      - run: cd build && git init
      - run: cd build && git remote add origin git@github.com:kjintroverted/dragon-ui.git
      - run: cd build && git checkout -b gh-pages
      - run: cd build && git add .
      - run: cd build && git config user.email "wkgreen13@gmail.com"
      - run: cd build && git config user.name "CircleCI"
      - run: cd build && git commit -m "CI Deploy"
      - run: cd build && git push -uf origin gh-pages

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          filters:
            branches:
              only: v2
